import { Unit, UnitDetail } from '../Unit'
import unitDetails from './_details/unitDetails'
    
export const Meter = new Unit("meter", UnitDetail.fromJSON(unitDetails['meter']))
export const Gramme = new Unit("gramme", UnitDetail.fromJSON(unitDetails['gramme']))
export const Litre = new Unit("litre", UnitDetail.fromJSON(unitDetails['litre']))
export const Second = new Unit("second", UnitDetail.fromJSON(unitDetails['second']))
export const Kelvin = new Unit("kelvin", UnitDetail.fromJSON(unitDetails['kelvin']))

export const Celsius = new Unit("celsius", UnitDetail.fromJSON(unitDetails['celsius']))
export const Fahrenheit = new Unit("fahrenheit", UnitDetail.fromJSON(unitDetails['fahrenheit']))

export const Thou = new Unit("thou", UnitDetail.fromJSON(unitDetails['thou']))
export const Inch = new Unit("inch", UnitDetail.fromJSON(unitDetails['inch']))
export const Foot = new Unit("foot", UnitDetail.fromJSON(unitDetails['foot']))
export const Yard = new Unit("yard", UnitDetail.fromJSON(unitDetails['yard']))
export const Chain = new Unit("chain", UnitDetail.fromJSON(unitDetails['chain']))
export const Furlong = new Unit("furlong", UnitDetail.fromJSON(unitDetails['furlong']))
export const Mile = new Unit("mile", UnitDetail.fromJSON(unitDetails['mile']))
export const League = new Unit("league", UnitDetail.fromJSON(unitDetails['league']))

export const Pound = new Unit("pound", UnitDetail.fromJSON(unitDetails['pound']))
export const Grain = new Unit("grain", UnitDetail.fromJSON(unitDetails['grain']))
export const Drachm = new Unit("drachm", UnitDetail.fromJSON(unitDetails['drachm']))
export const Dram = new Unit("dram", UnitDetail.fromJSON(unitDetails['dram']))
export const Ounce = new Unit("ounce", UnitDetail.fromJSON(unitDetails['ounce']))
export const Stone = new Unit("stone", UnitDetail.fromJSON(unitDetails['stone']))
export const Quarter = new Unit("quarter", UnitDetail.fromJSON(unitDetails['quarter']))
export const Hundredweight = new Unit("hundredweight", UnitDetail.fromJSON(unitDetails['hundredweight']))
export const Ton = new Unit("ton", UnitDetail.fromJSON(unitDetails['ton']))

export const GasMark = new Unit("gas-mark", UnitDetail.fromJSON(unitDetails['gas-mark']))

export const Minim = new Unit("minim", UnitDetail.fromJSON(unitDetails['minim']))
export const FluidScruple = new Unit("fluid-scruple", UnitDetail.fromJSON(unitDetails['fluid-scruple']))
export const FluidDrachm = new Unit("fluid-drachm", UnitDetail.fromJSON(unitDetails['fluid-drachm']))
export const FluidDram = new Unit("fluid-dram", UnitDetail.fromJSON(unitDetails['fluid-dram']))
export const FluidOunce = new Unit("fluid-ounce", UnitDetail.fromJSON(unitDetails['fluid-ounce']))
export const Gill = new Unit("gill", UnitDetail.fromJSON(unitDetails['gill']))
export const Pint = new Unit("pint", UnitDetail.fromJSON(unitDetails['pint']))
export const Quart = new Unit("quart", UnitDetail.fromJSON(unitDetails['quart']))
export const Gallon = new Unit("gallon", UnitDetail.fromJSON(unitDetails['gallon']))

export const Drop = new Unit("drop", UnitDetail.fromJSON(unitDetails['drop']))
export const Teaspoon = new Unit("teaspoon", UnitDetail.fromJSON(unitDetails['teaspoon']))
export const Dessertspoon = new Unit("dessertspoon", UnitDetail.fromJSON(unitDetails['dessertspoon']))
export const Tablespoon = new Unit("tablespoon", UnitDetail.fromJSON(unitDetails['tablespoon']))
export const Cup = new Unit("cup", UnitDetail.fromJSON(unitDetails['cup']))
export const Go  = new Unit("go", UnitDetail.fromJSON(unitDetails['go']))

export const KingSize = new Unit("king-size", UnitDetail.fromJSON(unitDetails['king-size']))
export const Jumbo = new Unit("jumbo", UnitDetail.fromJSON(unitDetails['jumbo']))
export const VeryLarge = new Unit("very-large", UnitDetail.fromJSON(unitDetails['very-large']))
export const Large = new Unit("large", UnitDetail.fromJSON(unitDetails['large']))
export const Medium = new Unit("medium", UnitDetail.fromJSON(unitDetails['medium']))
export const Small = new Unit("small", UnitDetail.fromJSON(unitDetails['small']))
export const Peewee = new Unit("peewee", UnitDetail.fromJSON(unitDetails['peewee']))

export const SizeEightEgg = new Unit("size-8-egg", UnitDetail.fromJSON(unitDetails['size-8-egg']))
export const SizeSevenEgg = new Unit("size-7-egg", UnitDetail.fromJSON(unitDetails['size-7-egg']))
export const SizeSixEgg = new Unit("size-6-egg", UnitDetail.fromJSON(unitDetails['size-6-egg']))
export const SizeFiveEgg = new Unit("size-5-egg", UnitDetail.fromJSON(unitDetails['size-5-egg']))
export const SizeFourEgg = new Unit("size-4-egg", UnitDetail.fromJSON(unitDetails['size-4-egg']))

export const Stick = new Unit("stick", UnitDetail.fromJSON(unitDetails['stick']))
