import { Unit, UnitDetails } from '../Unit'
import unitDetails from './unitDetails.json'
    
export const Meter = new Unit("meter", UnitDetails.fromJSON(unitDetails['meter']))
export const Gramme = new Unit("gramme", UnitDetails.fromJSON(unitDetails['gramme']))
export const Litre = new Unit("litre", UnitDetails.fromJSON(unitDetails['litre']))
export const Second = new Unit("second", UnitDetails.fromJSON(unitDetails['second']))
export const Kelvin = new Unit("kelvin", UnitDetails.fromJSON(unitDetails['kelvin']))

export const Celsius = new Unit("celsius", UnitDetails.fromJSON(unitDetails['celsius']))
export const Fahrenheit = new Unit("fahrenheit", UnitDetails.fromJSON(unitDetails['fahrenheit']))

export const Thou = new Unit("thou", UnitDetails.fromJSON(unitDetails['thou']))
export const Inch = new Unit("inch", UnitDetails.fromJSON(unitDetails['inch']))
export const Foot = new Unit("foot", UnitDetails.fromJSON(unitDetails['foot']))
export const Yard = new Unit("yard", UnitDetails.fromJSON(unitDetails['yard']))
export const Chain = new Unit("chain", UnitDetails.fromJSON(unitDetails['chain']))
export const Furlong = new Unit("furlong", UnitDetails.fromJSON(unitDetails['furlong']))
export const Mile = new Unit("mile", UnitDetails.fromJSON(unitDetails['mile']))
export const League = new Unit("league", UnitDetails.fromJSON(unitDetails['league']))

export const Pound = new Unit("pound", UnitDetails.fromJSON(unitDetails['pound']))
export const Grain = new Unit("grain", UnitDetails.fromJSON(unitDetails['grain']))
export const Drachm = new Unit("drachm", UnitDetails.fromJSON(unitDetails['drachm']))
export const Dram = new Unit("dram", UnitDetails.fromJSON(unitDetails['dram']))
export const Ounce = new Unit("ounce", UnitDetails.fromJSON(unitDetails['ounce']))
export const Stone = new Unit("stone", UnitDetails.fromJSON(unitDetails['stone']))
export const Quarter = new Unit("quarter", UnitDetails.fromJSON(unitDetails['quarter']))
export const Hundredweight = new Unit("hundredweight", UnitDetails.fromJSON(unitDetails['hundredweight']))
export const Ton = new Unit("ton", UnitDetails.fromJSON(unitDetails['ton']))

export const GasMark = new Unit("gas-mark", UnitDetails.fromJSON(unitDetails['gas-mark']))

export const Minim = new Unit("minim", UnitDetails.fromJSON(unitDetails['minim']))
export const FluidScruple = new Unit("fluid-scruple", UnitDetails.fromJSON(unitDetails['fluid-scruple']))
export const FluidDrachm = new Unit("fluid-drachm", UnitDetails.fromJSON(unitDetails['fluid-drachm']))
export const FluidDram = new Unit("fluid-dram", UnitDetails.fromJSON(unitDetails['fluid-dram']))
export const FluidOunce = new Unit("fluid-ounce", UnitDetails.fromJSON(unitDetails['fluid-ounce']))
export const Gill = new Unit("gill", UnitDetails.fromJSON(unitDetails['gill']))
export const Pint = new Unit("pint", UnitDetails.fromJSON(unitDetails['pint']))
export const Quart = new Unit("quart", UnitDetails.fromJSON(unitDetails['quart']))
export const Gallon = new Unit("gallon", UnitDetails.fromJSON(unitDetails['gallon']))

export const Drop = new Unit("drop", UnitDetails.fromJSON(unitDetails['drop']))
export const Teaspoon = new Unit("teaspoon", UnitDetails.fromJSON(unitDetails['teaspoon']))
export const Dessertspoon = new Unit("dessertspoon", UnitDetails.fromJSON(unitDetails['dessertspoon']))
export const Tablespoon = new Unit("tablespoon", UnitDetails.fromJSON(unitDetails['tablespoon']))
export const Cup = new Unit("cup", UnitDetails.fromJSON(unitDetails['cup']))
export const Go  = new Unit("go", UnitDetails.fromJSON(unitDetails['go']))

export const KingSize = new Unit("king-size", UnitDetails.fromJSON(unitDetails['king-size']))
export const Jumbo = new Unit("jumbo", UnitDetails.fromJSON(unitDetails['jumbo']))
export const VeryLarge = new Unit("very-large", UnitDetails.fromJSON(unitDetails['very-large']))
export const Large = new Unit("large", UnitDetails.fromJSON(unitDetails['large']))
export const Medium = new Unit("medium", UnitDetails.fromJSON(unitDetails['medium']))
export const Small = new Unit("small", UnitDetails.fromJSON(unitDetails['small']))
export const Peewee = new Unit("peewee", UnitDetails.fromJSON(unitDetails['peewee']))

export const SizeEightEgg = new Unit("size-8-egg", UnitDetails.fromJSON(unitDetails['size-8-egg']))
export const SizeSevenEgg = new Unit("size-7-egg", UnitDetails.fromJSON(unitDetails['size-7-egg']))
export const SizeSixEgg = new Unit("size-6-egg", UnitDetails.fromJSON(unitDetails['size-6-egg']))
export const SizeFiveEgg = new Unit("size-5-egg", UnitDetails.fromJSON(unitDetails['size-5-egg']))
export const SizeFourEgg = new Unit("size-4-egg", UnitDetails.fromJSON(unitDetails['size-4-egg']))

export const Stick = new Unit("stick", UnitDetails.fromJSON(unitDetails['stick']))
