import { Unit, UnitDetail } from '../Unit'
import unitDetails from './_details/unitDetails'
import * as usages from './usages'
    
export const Meter = new Unit("meter", 0, [usages.Science], UnitDetail.fromJSON(unitDetails['meter']))
export const Gramme = new Unit("gramme", 0, [usages.Science, usages.Cookery], UnitDetail.fromJSON(unitDetails['gramme']))
export const Litre = new Unit("litre", 0, [usages.Science, usages.Cookery], UnitDetail.fromJSON(unitDetails['litre']))
export const Second = new Unit("second", 0, [usages.Science, usages.Cookery], UnitDetail.fromJSON(unitDetails['second']))
export const Kelvin = new Unit("kelvin", 0, [usages.Science], UnitDetail.fromJSON(unitDetails['kelvin']))

export const Celsius = new Unit("celsius", 0, [usages.Science, usages.Cookery], UnitDetail.fromJSON(unitDetails['celsius']))
export const Fahrenheit = new Unit("fahrenheit", 0, [usages.Science, usages.Cookery], UnitDetail.fromJSON(unitDetails['fahrenheit']))
export const GasMark = new Unit("gas-mark", 0, [usages.Cookery], UnitDetail.fromJSON(unitDetails['gas-mark']))

export const Thou = new Unit("thou", -2, [usages.Science], UnitDetail.fromJSON(unitDetails['thou']))
export const Inch = new Unit("inch", -1, [usages.Science, usages.Cookery], UnitDetail.fromJSON(unitDetails['inch']))
export const Foot = new Unit("foot", 0, [usages.Science], UnitDetail.fromJSON(unitDetails['foot']))
export const Yard = new Unit("yard", 1, [usages.Science], UnitDetail.fromJSON(unitDetails['yard']))
export const Chain = new Unit("chain", 2, [usages.Science], UnitDetail.fromJSON(unitDetails['chain']))
export const Furlong = new Unit("furlong", 3, [usages.Science], UnitDetail.fromJSON(unitDetails['furlong']))
export const Mile = new Unit("mile", 4, [usages.Science], UnitDetail.fromJSON(unitDetails['mile']))
export const League = new Unit("league", 5, [usages.Science], UnitDetail.fromJSON(unitDetails['league']))

export const Grain = new Unit("grain", -3, [usages.Science, usages.Cookery], UnitDetail.fromJSON(unitDetails['grain']))
export const Drachm = new Unit("drachm", -2, [usages.Science, usages.Cookery], UnitDetail.fromJSON(unitDetails['drachm']))
export const Dram = new Unit("dram", -2, [usages.Science, usages.Cookery], UnitDetail.fromJSON(unitDetails['dram']))
export const Ounce = new Unit("ounce", -1, [usages.Science, usages.Cookery], UnitDetail.fromJSON(unitDetails['ounce']))
export const Pound = new Unit("pound", 0, [usages.Science], UnitDetail.fromJSON(unitDetails['pound']))
export const Stone = new Unit("stone", 1, [usages.Science], UnitDetail.fromJSON(unitDetails['stone']))
export const Quarter = new Unit("quarter", 2, [usages.Science], UnitDetail.fromJSON(unitDetails['quarter']))
export const Hundredweight = new Unit("hundredweight", 3, [usages.Science], UnitDetail.fromJSON(unitDetails['hundredweight']))
export const Ton = new Unit("ton", 4, [usages.Science], UnitDetail.fromJSON(unitDetails['ton']))

export const Minim = new Unit("minim", -3, [usages.Science], UnitDetail.fromJSON(unitDetails['minim']))
export const FluidScruple = new Unit("fluid-scruple", -2, [usages.Science], UnitDetail.fromJSON(unitDetails['fluid-scruple']))
export const FluidDrachm = new Unit("fluid-drachm", 1, [usages.Science], UnitDetail.fromJSON(unitDetails['fluid-drachm']))
export const FluidDram = new Unit("fluid-dram", -1, [usages.Science], UnitDetail.fromJSON(unitDetails['fluid-dram']))
export const FluidOunce = new Unit("fluid-ounce", 0, [usages.Science, usages.Cookery], UnitDetail.fromJSON(unitDetails['fluid-ounce']))
export const Gill = new Unit("gill", 1, [usages.Science], UnitDetail.fromJSON(unitDetails['gill']))
export const Pint = new Unit("pint", 2, [usages.Science, usages.Cookery], UnitDetail.fromJSON(unitDetails['pint']))
export const Quart = new Unit("quart", 3, [usages.Science, usages.Cookery], UnitDetail.fromJSON(unitDetails['quart']))
export const Gallon = new Unit("gallon", 4, [usages.Science, usages.Cookery], UnitDetail.fromJSON(unitDetails['gallon']))

export const Drop = new Unit("drop", -1, [usages.Cookery], UnitDetail.fromJSON(unitDetails['drop']))
export const Teaspoon = new Unit("teaspoon", 0, [usages.Cookery], UnitDetail.fromJSON(unitDetails['teaspoon']))
export const Dessertspoon = new Unit("dessertspoon", 1, [usages.Cookery], UnitDetail.fromJSON(unitDetails['dessertspoon']))
export const Tablespoon = new Unit("tablespoon", 2, [usages.Cookery], UnitDetail.fromJSON(unitDetails['tablespoon']))
export const Cup = new Unit("cup", 3, [usages.Cookery], UnitDetail.fromJSON(unitDetails['cup']))
export const Go  = new Unit("go", 3, [usages.Cookery], UnitDetail.fromJSON(unitDetails['go']))

export const KingSize = new Unit("king-size", 4, [usages.Cookery], UnitDetail.fromJSON(unitDetails['king-size']))
export const Jumbo = new Unit("jumbo", 3, [usages.Cookery], UnitDetail.fromJSON(unitDetails['jumbo']))
export const VeryLarge = new Unit("very-large", 2, [usages.Cookery], UnitDetail.fromJSON(unitDetails['very-large']))
export const Large = new Unit("large", 1, [usages.Cookery], UnitDetail.fromJSON(unitDetails['large']))
export const Medium = new Unit("medium", 0, [usages.Cookery], UnitDetail.fromJSON(unitDetails['medium']))
export const Small = new Unit("small", -1, [usages.Cookery], UnitDetail.fromJSON(unitDetails['small']))
export const Peewee = new Unit("peewee", -2, [usages.Cookery], UnitDetail.fromJSON(unitDetails['peewee']))

export const SizeEightEgg = new Unit("size-8-egg", 2, [usages.Cookery], UnitDetail.fromJSON(unitDetails['size-8-egg']))
export const SizeSevenEgg = new Unit("size-7-egg", 1, [usages.Cookery], UnitDetail.fromJSON(unitDetails['size-7-egg']))
export const SizeSixEgg = new Unit("size-6-egg", 0, [usages.Cookery], UnitDetail.fromJSON(unitDetails['size-6-egg']))
export const SizeFiveEgg = new Unit("size-5-egg", -1, [usages.Cookery], UnitDetail.fromJSON(unitDetails['size-5-egg']))
export const SizeFourEgg = new Unit("size-4-egg", -2, [usages.Cookery], UnitDetail.fromJSON(unitDetails['size-4-egg']))

export const Stick = new Unit("stick", 0, [usages.Cookery], UnitDetail.fromJSON(unitDetails['stick']))
